{% set name = "tftest" %}
{% set version = "1.8.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/tftest-{{ version }}.tar.gz
  sha256: 278b9ee093b2a9e7278d91f885c909495b8c0b08ce5c5adbcac5de7700ae5c79

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.6
    - nose >=1.3
    - pip
  run:
    - python >=3.6

test:
  imports:
    - tftest
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/GoogleCloudPlatform/terraform-python-testing-helper
  summary: Simple Terraform test helper
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - dangercrow
