{% set name = "tftest" %}
{% set version = "1.8.7" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/tftest-{{ version }}.tar.gz
  sha256: c1d3bc6800cf9dfc86e9790369f681308f29e8e92b7eefd230ac522897e6aaed

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.6
    - nose >=1.3
    - pip
  run:
    - python >=3.6

test:
  imports:
    - tftest
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/GoogleCloudPlatform/terraform-python-testing-helper
  summary: Simple Terraform test helper
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - dangercrow
